# BlockPower Confiq.
# By TheNote.

# BlockPower ID. ID list: http://minecraft-ids.grahamedgecombe.com/
Block: 152

# BlockPower Stärke
BlockPower: 0.8

# Aktiviere/Deaktiviere Feuerparticle. 
Particle: true
